<a href="https://colab.research.google.com/github/ydebessu/handson/blob/main/nnp/02hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nnfs

In [2]:
from nnfs.datasets import spiral_data
import numpy as np
import matplotlib.pyplot as plt
import nnfs
nnfs.init()

In [3]:
# Generate data from spiral_data with three classes and plot with scatter colored rgb for each class

# X, y = spiral_data(samples=100, classes=3)
# print(f'X shape: {X.shape}')
# print(f'X type: {type(X)}')
# print(f'y shape: {y.shape}')
# print(f'y type: {type(y)}')
# plt.scatter(X[:, 0], X[:, 1], c=y, cmap='brg')
# plt.show()

## Adding Layers

In [4]:
class Layer_Dense:
  """
  A dense layer with weights and biases.
  """
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))

  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = np.dot(inputs, self.weights) + self.biases

  def backward(self, dvalues):
    # Calculate gradients
    self.dweights = np.dot(self.inputs.T, dvalues)
    self.dbiases = np.sum(dvalues, axis=0, keepdims=True)
    self.dinputs = np.dot(dvalues, self.weights.T)


## Activation

In [5]:
# ReLU Activation class
class Activation_ReLU:
  def forward(self, inputs):
    # Calculate output values from inputs
    self.output = np.maximum(0, inputs)

  def backward(self, dvalues):
    # Calculate gradients
    self.dinputs = dvalues.copy()
    self.dinputs[self.inputs <= 0] = 0

class Activation_Softmax:
  def forward(self, inputs):
    # Calculate output values from inputs
    exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    self.output = probabilities

## Loss Function

In [6]:
class Loss:
  def calculate(self, output, y):
    # Calculate the data and regularization losses given model output and ground truth values
    sample_losses = self.forward(output, y)
    data_loss = np.mean(sample_losses)
    return data_loss

class Loss_CategoricalCrossentropy(Loss):
  def forward(self, y_pred, y_true):
    # Calculate cross-entropy loss
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
    if len(y_true.shape) == 1:
      correct_confidences = y_pred_clipped[range(samples), y_true]
    elif len(y_true.shape) == 2:
      correct_confidences = np.sum(y_pred_clipped * y_true, axis=1)
    negative_log_likelihoods = -np.log(correct_confidences)
    return negative_log_likelihoods

  def backward(self, dvalues, y_true):
    # Calculate gradient
    samples = len(dvalues)
    labels = len(dvalues[0])
    if len(y_true.shape) == 1:
      y_true = np.eye(labels)[y_true]

    self.dinputs = -y_true / dvalues
    self.dinputs = self.dinputs / samples


## Example

In [7]:
# Create a dense layer with 2 input features and 3 neurons
class_size = 3
X, y = spiral_data(samples=100, classes=class_size)
input_size = X.shape[1]
hdim = 3

layer1 = Layer_Dense(input_size, hdim)
layer2 = Layer_Dense(hdim, class_size)
activation1 = Activation_ReLU()
activation2 = Activation_Softmax()
loss_function = Loss_CategoricalCrossentropy()

print(f"Layer 1 weights: {layer1.weights}")
print(f"Layer 1 bias: {layer1.biases}")
layer1.forward(X)
activation1.forward(layer1.output)
layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output[:5])
loss = loss_function.calculate(activation2.output, y)
print(f"Loss: {loss}")

predictions = np.argmax(activation2.output, axis=1)
if len(y.shape) == 2:
  y = np.argmax(y, axis=1)
accuracy = np.mean(predictions==y)
print(f"Accuracy: {accuracy}")


Layer 1 weights: [[-0.01306527  0.01658131 -0.00118164]
 [-0.00680178  0.00666383 -0.0046072 ]]
Layer 1 bias: [[0. 0. 0.]]
[[0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.33333364]
 [0.3333329  0.33333293 0.3333342 ]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
Loss: 1.0986104011535645
Accuracy: 0.34
